#! /bin/bash

password="ptr*1$#+22A"

if [[ ${#password} -ge 8 && "$password" || *[A-Z]* || "$password" || *[a-z]* || "$password" || *[0-9]* && "$password" || *[*$#+]* ]]
then
    echo "pass"
else
    echo "fail"
fi
